default: Vysyx_24070016_top

include Vysyx_24070016_top.mk

# Include variables and rules generated by menuconfig
-include $(NPC_HOME)/csrc/include/config/auto.conf
-include $(NPC_HOME)/csrc/include/config/auto.conf.cmd

GUEST_ISA = riscv32e
CXXFLAGS += -MMD -O3 -std=c++17 -fno-exceptions -fPIE -Wno-unused-result -D__GUEST_ISA__=$(GUEST_ISA)
# CXXFLAGS += $(shell llvm-config-11 --cxxflags) -fPIC 
CXXFLAGS += $(if $(CONFIG_CC_ASAN),-fsanitize=address,)
# CXXFLAGS += -fsanitize=address
# LDFLAGS += -fsanitize=address
LDFLAGS += -O3 -rdynamic -shared -fPIC
LDLIBS += -lSDL2
LIBS += $(shell llvm-config-11 --libs)
LIBS += -lreadline -ldl -pie -lSDL2
LINK := g++